### ISSUE TITLE
Compression very slow with large number of files

### ISSUE THREAD

**Issue by lbucao** [phillipp/SevenZipSharp#4]
I'm running `SevenZipCompressor#CompressStreamDictionary(...)` and noticed this has non-linear performance degradation as I add more files to the dictionary.

I ran a profiler while compressing 1 million 100KB files and it looks like the vast majority of the time is spent in `ArchiveUpdateCallback#SetOperationResult(...)`. 

![image](https://cloud.githubusercontent.com/assets/2163603/15444046/75e9057e-1eb2-11e6-8b84-3e8c45587388.png)

Further digging showed this time is spent doing GC which appears to be manually invoked after every single file is compressed.

Can we stop calling or greatly reduce calls to `GC.Collect()` in `SetOperationResult(...)`?

**Comment by phillipp** [comment]
Sorry, this repo is absolutely unmaintained. It looks like it is still active on on codeplex: https://sevenzipsharp.codeplex.com/
